// Mocks generated by Mockito 5.2.0 from annotations
// in technical_assignment/test/widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:technical_assignment/model/user_model.dart' as _i4;
import 'package:technical_assignment/view_model/home_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepository extends _i1.Mock implements _i2.HomeRepository {
  @override
  _i3.Future<List<_i4.UserModel>?> fetchUsers() =>
      (super.noSuchMethod(Invocation.method(#fetchUsers, []),
              returnValue: Future<List<_i4.UserModel>?>.value())
          as _i3.Future<List<_i4.UserModel>?>);
}
